### ISSUE TITLE
Cancelable Network requests

### ISSUE THREAD

**Issue by MichaelMcGuire** [ashfurrow/Moya#119]
The current API does not provide a way to cancel a network request.  Alamofire's `Request` object exposes `NSURLSessionTasks`'s `cancel` method, but `MoyaProvider` does not keep a reference to the `Request` object to later cancel, nor does it return a token to the client that could be passed later for canceling.

Since supporting this would require a change to the API, I was wondering what your thoughts were on supporting this?  I wouldn't mind helping out if you wanted to have some discussion on how this would look.

**Comment by ashfurrow** [comment]
Neat idea!

I think the base case for non-Reactive providers would be to return an opaque object; one that has no public members except a `cancel()` function. The object (or struct) would wrap the `Request` object from Alamofire to avoid a leaky abstraction. Then it would be up to the caller to do anything – or not – with the returned value. 

It wouldn't even be a breaking change, unless the call to `request()` was the online line in a closure that has a `Void` return value. 

For the Reactive extension, it's a bit trickier but not difficult. We currently have a side-effect that if the subscription to the signal is cancelled before the request finishes, we remove the request from the inflight cache. We would just need to add a call to `cancel()` [here](https://github.com/ashfurrow/Moya/blob/ad1e2266e8820433270eca3ba98aa01c787879a3/Moya%2BReactiveCocoa.swift#L74-L79).

**Comment by MichaelMcGuire** [comment]
Perfect :ok_hand: 

I can take a look at this in the next couple of days, unless you'd like to handle it.  If you'd like me to start something, let me know which version of Xcode you prefer for the work on master.  I'm assuming 6.1.1? 6.2?

**Comment by MichaelMcGuire** [comment]
Couple of questions:

1. Do you expect this functionality to work with stubbed responses?  If so, I'm assuming it would only be in the case of a .Delayed behavior, as anything else instantly responds
2. What would you expect to happen in regards to the completion block when a request is canceled?  My first inclination would be to still call the completion block but with an error. I believe that is the behavior of the `NSURLSessionTask`.

**Comment by ashfurrow** [comment]
Great questions! 

1. Hmm. Good question. I think `.Delayed` makes sense. 
1. This is a really interesting point. I really dislike having a tonne of different parameters in the completion block and making the user of the library try to figure out what they all mean, but my primary use of Moya is with ReactiveCocoa, so I only wrapped Alamofire (figured those people know what's best). In this case, I think we should stick as close to the behaviour as possible. If `NSURLSessionTask` completes with an error, then :+1:. It might not even be necessary to do that, since Moya uses their completion block to invoke its completion, so maybe cancelling the task is sufficient to have Alamofire call Moya, which calls its completion. Thoughts? 
1. Yeah, keeping it as-is is perfect. It's more like "is a request inflight" more than anything.

**Comment by ashfurrow** [comment]
Oh, and let's go on the latest Xcode – we can merge into the `swift-1.2` branch, which'll be merged into master shortly anyway.

**Comment by MichaelMcGuire** [comment]
I ended up using Xcode 6.1.1 because the latest Xcode (with Swift 1.2) won't compile without the changes from the `swift-1.2` branch.
