### ISSUE TITLE
Track ReactiveCocoa releases

### ISSUE THREAD

**Issue by tp** [ashfurrow/Moya#153]
Is there a policy on tracking dependency releases?

RC is on beta 8 while adding Moya required my project to go back to beta 6 (using Carthage).

**Comment by orta** [comment]
To my knowledge, no-one has stepped up to keep the Carthage/RAC branch in sync, we'd welcome a PR making sure it supports the latest from you.

**Comment by ashfurrow** [comment]
Yeah, to be honest I'm not entirely sure how dependency resolution with Carthage works. If it were CocoaPods, I'd fork the Moya repo and point to my fork in the Podfile. 

@neonichu: you added Carthage support – any ideas?

**Comment by aschuch** [comment]
Yes you can definitely just fork Moya, change the ReactiveCocoa branch in the Cartfile and you are good to go.

To add more context: The problem here is that the ReactiveCocoa beta is referenced using its specific github branch.
I think we should simply add a version requirement to the major version of ReactiveCocoa, so that Carthage has a bit more room to decide which version of ReactiveCocoa to use.

```
github "ReactiveCocoa/ReactiveCocoa" ~> 3.0
```

**Comment by neonichu** [comment]
@aschuch sounds good, do you want to make a PR for that?

**Comment by ashfurrow** [comment]
Cool, thanks @aschuch ! I wasn't sure how the `~> 3.0` signifier works in Carthage.
